language: python
sudo: false
cache: pip

addons:
  apt:
    packages:
      - gfortran
      - libatlas-dev
      - libatlas-base-dev

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

before_install:
  - pip install pip setuptools --upgrade

install:
  - pip install .\[all\]

script:
  - py.test --cov fishrast --cov-report term-missing
